### PR TITLE
Closes Deleting Selected Element Bug

### LINKED ISSUE #109: Deleting Selected Item Bug
If the Item selected is deleted, the element isn't deleted and there's an error in the browser console

### PR DESCRIPTION
**Pull request by illuminatedspace**
adds a method to canvas container that checks to see if selected matches elementToDelete. If it does, selected is cleared before delete.
closes #109

### CODE REVIEW

File: app/components/Canvas.js [hunk 1]
```diff
@@ -39,11 +39,16 @@ class Canvas extends Component {
   }
 
   render() {
+    console.log('PROPS IN CANVAS', this.props)
```
Comment (clairefreehafer) [inline app/components/Canvas.js]: console.log

File: app/components/CanvasContainer.js [hunk 2]
```diff
@@ -42,6 +43,17 @@ export default class CanvasContainer extends Component {
     })
   }
 
+  //this function gets passed down to Page so that selected is cleared before delete
+  //otherwise there is a bug when you delete the currently selected element
+  clearSelectedIfDeleted (type, id) {
+    const selected = this.state.selected
+    console.log('CLEARING SELECTED IF DELETED')
```
Comment (clairefreehafer) [inline app/components/CanvasContainer.js]: 2 console longs in this function

File: app/components/Page.js [hunk 3]
```diff
@@ -45,14 +45,15 @@ class Page extends Component {
   }
 
   moveElement(type, id, left, top) {
-
-
+    console.log('PROPS IN PAGE', this.props)
```
Comment (clairefreehafer) [inline app/components/Page.js]: console.log

**Review by clairefreehafer — CHANGES_REQUESTED** [review]
console logs
